# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Online Banking Walkthrough
email: webmaster@afcu.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
host: 0.0.0.0
url: "http://olb.afcu.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
port: 3000
opentip: 'data-ot-delay="0" data-ot-group="tags" data-ot-background="#307FE2"'

# Build settings
markdown: kramdown
